---
kind: pipeline
name: default
type: docker

trigger:
  event:
    - push

steps:
  - name: get_tags
    image: alpine/git
    commands:
      - git fetch --tags
  - name: docker
    image: plugins/docker
    settings:
      registry: registry.freedomcore.ru
      repo: registry.freedomcore.ru/freedomcore/micro-redis
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - latest
  - name: webhook
    image: plugins/webhook
    failure: ignore
    settings:
      urls:
        from_secret: webhook