// Code generated by protoc-gen-go. DO NOT EDIT.
// source: redis.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RedisEmpty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RedisEmpty) Reset()         { *m = RedisEmpty{} }
func (m *RedisEmpty) String() string { return proto.CompactTextString(m) }
func (*RedisEmpty) ProtoMessage()    {}
func (*RedisEmpty) Descriptor() ([]byte, []int) {
	return fileDescriptor_d954120a2319ff8f, []int{0}
}

func (m *RedisEmpty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedisEmpty.Unmarshal(m, b)
}
func (m *RedisEmpty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedisEmpty.Marshal(b, m, deterministic)
}
func (m *RedisEmpty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedisEmpty.Merge(m, src)
}
func (m *RedisEmpty) XXX_Size() int {
	return xxx_messageInfo_RedisEmpty.Size(m)
}
func (m *RedisEmpty) XXX_DiscardUnknown() {
	xxx_messageInfo_RedisEmpty.DiscardUnknown(m)
}

var xxx_messageInfo_RedisEmpty proto.InternalMessageInfo

type Duration struct {
	Seconds              int64    `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	Nanos                int32    `protobuf:"varint,2,opt,name=nanos,proto3" json:"nanos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Duration) Reset()         { *m = Duration{} }
func (m *Duration) String() string { return proto.CompactTextString(m) }
func (*Duration) ProtoMessage()    {}
func (*Duration) Descriptor() ([]byte, []int) {
	return fileDescriptor_d954120a2319ff8f, []int{1}
}

func (m *Duration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Duration.Unmarshal(m, b)
}
func (m *Duration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Duration.Marshal(b, m, deterministic)
}
func (m *Duration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Duration.Merge(m, src)
}
func (m *Duration) XXX_Size() int {
	return xxx_messageInfo_Duration.Size(m)
}
func (m *Duration) XXX_DiscardUnknown() {
	xxx_messageInfo_Duration.DiscardUnknown(m)
}

var xxx_messageInfo_Duration proto.InternalMessageInfo

func (m *Duration) GetSeconds() int64 {
	if m != nil {
		return m.Seconds
	}
	return 0
}

func (m *Duration) GetNanos() int32 {
	if m != nil {
		return m.Nanos
	}
	return 0
}

type SetRedisObject struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Expiration           int64    `protobuf:"varint,3,opt,name=expiration,proto3" json:"expiration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetRedisObject) Reset()         { *m = SetRedisObject{} }
func (m *SetRedisObject) String() string { return proto.CompactTextString(m) }
func (*SetRedisObject) ProtoMessage()    {}
func (*SetRedisObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_d954120a2319ff8f, []int{2}
}

func (m *SetRedisObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetRedisObject.Unmarshal(m, b)
}
func (m *SetRedisObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetRedisObject.Marshal(b, m, deterministic)
}
func (m *SetRedisObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetRedisObject.Merge(m, src)
}
func (m *SetRedisObject) XXX_Size() int {
	return xxx_messageInfo_SetRedisObject.Size(m)
}
func (m *SetRedisObject) XXX_DiscardUnknown() {
	xxx_messageInfo_SetRedisObject.DiscardUnknown(m)
}

var xxx_messageInfo_SetRedisObject proto.InternalMessageInfo

func (m *SetRedisObject) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SetRedisObject) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *SetRedisObject) GetExpiration() int64 {
	if m != nil {
		return m.Expiration
	}
	return 0
}

type IncrementDecrementRedis struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                int64    `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IncrementDecrementRedis) Reset()         { *m = IncrementDecrementRedis{} }
func (m *IncrementDecrementRedis) String() string { return proto.CompactTextString(m) }
func (*IncrementDecrementRedis) ProtoMessage()    {}
func (*IncrementDecrementRedis) Descriptor() ([]byte, []int) {
	return fileDescriptor_d954120a2319ff8f, []int{3}
}

func (m *IncrementDecrementRedis) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IncrementDecrementRedis.Unmarshal(m, b)
}
func (m *IncrementDecrementRedis) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IncrementDecrementRedis.Marshal(b, m, deterministic)
}
func (m *IncrementDecrementRedis) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncrementDecrementRedis.Merge(m, src)
}
func (m *IncrementDecrementRedis) XXX_Size() int {
	return xxx_messageInfo_IncrementDecrementRedis.Size(m)
}
func (m *IncrementDecrementRedis) XXX_DiscardUnknown() {
	xxx_messageInfo_IncrementDecrementRedis.DiscardUnknown(m)
}

var xxx_messageInfo_IncrementDecrementRedis proto.InternalMessageInfo

func (m *IncrementDecrementRedis) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *IncrementDecrementRedis) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type GetRedisKeys struct {
	Keys                 []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRedisKeys) Reset()         { *m = GetRedisKeys{} }
func (m *GetRedisKeys) String() string { return proto.CompactTextString(m) }
func (*GetRedisKeys) ProtoMessage()    {}
func (*GetRedisKeys) Descriptor() ([]byte, []int) {
	return fileDescriptor_d954120a2319ff8f, []int{4}
}

func (m *GetRedisKeys) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRedisKeys.Unmarshal(m, b)
}
func (m *GetRedisKeys) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRedisKeys.Marshal(b, m, deterministic)
}
func (m *GetRedisKeys) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRedisKeys.Merge(m, src)
}
func (m *GetRedisKeys) XXX_Size() int {
	return xxx_messageInfo_GetRedisKeys.Size(m)
}
func (m *GetRedisKeys) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRedisKeys.DiscardUnknown(m)
}

var xxx_messageInfo_GetRedisKeys proto.InternalMessageInfo

func (m *GetRedisKeys) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

type GetRedisKey struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRedisKey) Reset()         { *m = GetRedisKey{} }
func (m *GetRedisKey) String() string { return proto.CompactTextString(m) }
func (*GetRedisKey) ProtoMessage()    {}
func (*GetRedisKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_d954120a2319ff8f, []int{5}
}

func (m *GetRedisKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRedisKey.Unmarshal(m, b)
}
func (m *GetRedisKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRedisKey.Marshal(b, m, deterministic)
}
func (m *GetRedisKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRedisKey.Merge(m, src)
}
func (m *GetRedisKey) XXX_Size() int {
	return xxx_messageInfo_GetRedisKey.Size(m)
}
func (m *GetRedisKey) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRedisKey.DiscardUnknown(m)
}

var xxx_messageInfo_GetRedisKey proto.InternalMessageInfo

func (m *GetRedisKey) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type RedisResultString struct {
	Response             string   `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RedisResultString) Reset()         { *m = RedisResultString{} }
func (m *RedisResultString) String() string { return proto.CompactTextString(m) }
func (*RedisResultString) ProtoMessage()    {}
func (*RedisResultString) Descriptor() ([]byte, []int) {
	return fileDescriptor_d954120a2319ff8f, []int{6}
}

func (m *RedisResultString) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedisResultString.Unmarshal(m, b)
}
func (m *RedisResultString) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedisResultString.Marshal(b, m, deterministic)
}
func (m *RedisResultString) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedisResultString.Merge(m, src)
}
func (m *RedisResultString) XXX_Size() int {
	return xxx_messageInfo_RedisResultString.Size(m)
}
func (m *RedisResultString) XXX_DiscardUnknown() {
	xxx_messageInfo_RedisResultString.DiscardUnknown(m)
}

var xxx_messageInfo_RedisResultString proto.InternalMessageInfo

func (m *RedisResultString) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

type RedisResultFloat32 struct {
	Response             float32  `protobuf:"fixed32,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RedisResultFloat32) Reset()         { *m = RedisResultFloat32{} }
func (m *RedisResultFloat32) String() string { return proto.CompactTextString(m) }
func (*RedisResultFloat32) ProtoMessage()    {}
func (*RedisResultFloat32) Descriptor() ([]byte, []int) {
	return fileDescriptor_d954120a2319ff8f, []int{7}
}

func (m *RedisResultFloat32) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedisResultFloat32.Unmarshal(m, b)
}
func (m *RedisResultFloat32) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedisResultFloat32.Marshal(b, m, deterministic)
}
func (m *RedisResultFloat32) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedisResultFloat32.Merge(m, src)
}
func (m *RedisResultFloat32) XXX_Size() int {
	return xxx_messageInfo_RedisResultFloat32.Size(m)
}
func (m *RedisResultFloat32) XXX_DiscardUnknown() {
	xxx_messageInfo_RedisResultFloat32.DiscardUnknown(m)
}

var xxx_messageInfo_RedisResultFloat32 proto.InternalMessageInfo

func (m *RedisResultFloat32) GetResponse() float32 {
	if m != nil {
		return m.Response
	}
	return 0
}

type RedisResultFloat64 struct {
	Response             float64  `protobuf:"fixed64,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RedisResultFloat64) Reset()         { *m = RedisResultFloat64{} }
func (m *RedisResultFloat64) String() string { return proto.CompactTextString(m) }
func (*RedisResultFloat64) ProtoMessage()    {}
func (*RedisResultFloat64) Descriptor() ([]byte, []int) {
	return fileDescriptor_d954120a2319ff8f, []int{8}
}

func (m *RedisResultFloat64) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedisResultFloat64.Unmarshal(m, b)
}
func (m *RedisResultFloat64) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedisResultFloat64.Marshal(b, m, deterministic)
}
func (m *RedisResultFloat64) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedisResultFloat64.Merge(m, src)
}
func (m *RedisResultFloat64) XXX_Size() int {
	return xxx_messageInfo_RedisResultFloat64.Size(m)
}
func (m *RedisResultFloat64) XXX_DiscardUnknown() {
	xxx_messageInfo_RedisResultFloat64.DiscardUnknown(m)
}

var xxx_messageInfo_RedisResultFloat64 proto.InternalMessageInfo

func (m *RedisResultFloat64) GetResponse() float64 {
	if m != nil {
		return m.Response
	}
	return 0
}

type RedisResultInt struct {
	Response             int32    `protobuf:"varint,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RedisResultInt) Reset()         { *m = RedisResultInt{} }
func (m *RedisResultInt) String() string { return proto.CompactTextString(m) }
func (*RedisResultInt) ProtoMessage()    {}
func (*RedisResultInt) Descriptor() ([]byte, []int) {
	return fileDescriptor_d954120a2319ff8f, []int{9}
}

func (m *RedisResultInt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedisResultInt.Unmarshal(m, b)
}
func (m *RedisResultInt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedisResultInt.Marshal(b, m, deterministic)
}
func (m *RedisResultInt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedisResultInt.Merge(m, src)
}
func (m *RedisResultInt) XXX_Size() int {
	return xxx_messageInfo_RedisResultInt.Size(m)
}
func (m *RedisResultInt) XXX_DiscardUnknown() {
	xxx_messageInfo_RedisResultInt.DiscardUnknown(m)
}

var xxx_messageInfo_RedisResultInt proto.InternalMessageInfo

func (m *RedisResultInt) GetResponse() int32 {
	if m != nil {
		return m.Response
	}
	return 0
}

type RedisResultInt64 struct {
	Response             int64    `protobuf:"varint,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RedisResultInt64) Reset()         { *m = RedisResultInt64{} }
func (m *RedisResultInt64) String() string { return proto.CompactTextString(m) }
func (*RedisResultInt64) ProtoMessage()    {}
func (*RedisResultInt64) Descriptor() ([]byte, []int) {
	return fileDescriptor_d954120a2319ff8f, []int{10}
}

func (m *RedisResultInt64) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedisResultInt64.Unmarshal(m, b)
}
func (m *RedisResultInt64) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedisResultInt64.Marshal(b, m, deterministic)
}
func (m *RedisResultInt64) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedisResultInt64.Merge(m, src)
}
func (m *RedisResultInt64) XXX_Size() int {
	return xxx_messageInfo_RedisResultInt64.Size(m)
}
func (m *RedisResultInt64) XXX_DiscardUnknown() {
	xxx_messageInfo_RedisResultInt64.DiscardUnknown(m)
}

var xxx_messageInfo_RedisResultInt64 proto.InternalMessageInfo

func (m *RedisResultInt64) GetResponse() int64 {
	if m != nil {
		return m.Response
	}
	return 0
}

type RedisResultUInt64 struct {
	Response             uint64   `protobuf:"varint,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RedisResultUInt64) Reset()         { *m = RedisResultUInt64{} }
func (m *RedisResultUInt64) String() string { return proto.CompactTextString(m) }
func (*RedisResultUInt64) ProtoMessage()    {}
func (*RedisResultUInt64) Descriptor() ([]byte, []int) {
	return fileDescriptor_d954120a2319ff8f, []int{11}
}

func (m *RedisResultUInt64) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedisResultUInt64.Unmarshal(m, b)
}
func (m *RedisResultUInt64) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedisResultUInt64.Marshal(b, m, deterministic)
}
func (m *RedisResultUInt64) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedisResultUInt64.Merge(m, src)
}
func (m *RedisResultUInt64) XXX_Size() int {
	return xxx_messageInfo_RedisResultUInt64.Size(m)
}
func (m *RedisResultUInt64) XXX_DiscardUnknown() {
	xxx_messageInfo_RedisResultUInt64.DiscardUnknown(m)
}

var xxx_messageInfo_RedisResultUInt64 proto.InternalMessageInfo

func (m *RedisResultUInt64) GetResponse() uint64 {
	if m != nil {
		return m.Response
	}
	return 0
}

type RedisResultBoolean struct {
	Response             bool     `protobuf:"varint,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RedisResultBoolean) Reset()         { *m = RedisResultBoolean{} }
func (m *RedisResultBoolean) String() string { return proto.CompactTextString(m) }
func (*RedisResultBoolean) ProtoMessage()    {}
func (*RedisResultBoolean) Descriptor() ([]byte, []int) {
	return fileDescriptor_d954120a2319ff8f, []int{12}
}

func (m *RedisResultBoolean) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedisResultBoolean.Unmarshal(m, b)
}
func (m *RedisResultBoolean) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedisResultBoolean.Marshal(b, m, deterministic)
}
func (m *RedisResultBoolean) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedisResultBoolean.Merge(m, src)
}
func (m *RedisResultBoolean) XXX_Size() int {
	return xxx_messageInfo_RedisResultBoolean.Size(m)
}
func (m *RedisResultBoolean) XXX_DiscardUnknown() {
	xxx_messageInfo_RedisResultBoolean.DiscardUnknown(m)
}

var xxx_messageInfo_RedisResultBoolean proto.InternalMessageInfo

func (m *RedisResultBoolean) GetResponse() bool {
	if m != nil {
		return m.Response
	}
	return false
}

type RedisResultBytes struct {
	Response             []byte   `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RedisResultBytes) Reset()         { *m = RedisResultBytes{} }
func (m *RedisResultBytes) String() string { return proto.CompactTextString(m) }
func (*RedisResultBytes) ProtoMessage()    {}
func (*RedisResultBytes) Descriptor() ([]byte, []int) {
	return fileDescriptor_d954120a2319ff8f, []int{13}
}

func (m *RedisResultBytes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedisResultBytes.Unmarshal(m, b)
}
func (m *RedisResultBytes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedisResultBytes.Marshal(b, m, deterministic)
}
func (m *RedisResultBytes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedisResultBytes.Merge(m, src)
}
func (m *RedisResultBytes) XXX_Size() int {
	return xxx_messageInfo_RedisResultBytes.Size(m)
}
func (m *RedisResultBytes) XXX_DiscardUnknown() {
	xxx_messageInfo_RedisResultBytes.DiscardUnknown(m)
}

var xxx_messageInfo_RedisResultBytes proto.InternalMessageInfo

func (m *RedisResultBytes) GetResponse() []byte {
	if m != nil {
		return m.Response
	}
	return nil
}

func init() {
	proto.RegisterType((*RedisEmpty)(nil), "proto.RedisEmpty")
	proto.RegisterType((*Duration)(nil), "proto.Duration")
	proto.RegisterType((*SetRedisObject)(nil), "proto.SetRedisObject")
	proto.RegisterType((*IncrementDecrementRedis)(nil), "proto.IncrementDecrementRedis")
	proto.RegisterType((*GetRedisKeys)(nil), "proto.GetRedisKeys")
	proto.RegisterType((*GetRedisKey)(nil), "proto.GetRedisKey")
	proto.RegisterType((*RedisResultString)(nil), "proto.RedisResultString")
	proto.RegisterType((*RedisResultFloat32)(nil), "proto.RedisResultFloat32")
	proto.RegisterType((*RedisResultFloat64)(nil), "proto.RedisResultFloat64")
	proto.RegisterType((*RedisResultInt)(nil), "proto.RedisResultInt")
	proto.RegisterType((*RedisResultInt64)(nil), "proto.RedisResultInt64")
	proto.RegisterType((*RedisResultUInt64)(nil), "proto.RedisResultUInt64")
	proto.RegisterType((*RedisResultBoolean)(nil), "proto.RedisResultBoolean")
	proto.RegisterType((*RedisResultBytes)(nil), "proto.RedisResultBytes")
}

func init() { proto.RegisterFile("redis.proto", fileDescriptor_d954120a2319ff8f) }

var fileDescriptor_d954120a2319ff8f = []byte{
	// 530 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x94, 0x51, 0x6f, 0xd2, 0x50,
	0x14, 0xc7, 0xcb, 0x3a, 0x36, 0x38, 0x20, 0xc2, 0xd1, 0x65, 0xc8, 0xc3, 0x5c, 0xee, 0x13, 0x0f,
	0x06, 0xcd, 0xb6, 0x10, 0x25, 0x3e, 0x6c, 0x04, 0xdd, 0x88, 0x0f, 0x26, 0x45, 0x8c, 0xaf, 0x1d,
	0x3b, 0x31, 0x75, 0xe5, 0x5e, 0xd2, 0x7b, 0x41, 0xfb, 0x49, 0xfd, 0x3a, 0x86, 0x4b, 0x29, 0x97,
	0xdc, 0x16, 0x37, 0x7d, 0x5a, 0x6f, 0xfb, 0xff, 0xfd, 0xce, 0x39, 0xeb, 0xa1, 0x50, 0x89, 0xe8,
	0x2e, 0x90, 0x9d, 0x59, 0x24, 0x94, 0xc0, 0xa2, 0xfe, 0xc3, 0xaa, 0x00, 0xde, 0xf2, 0xee, 0x87,
	0xe9, 0x4c, 0xc5, 0xac, 0x07, 0xa5, 0xc1, 0x3c, 0xf2, 0x55, 0x20, 0x38, 0x36, 0xe1, 0x50, 0xd2,
	0x44, 0xf0, 0x3b, 0xd9, 0x2c, 0x9c, 0x16, 0xda, 0xae, 0xb7, 0x3e, 0xe2, 0x73, 0x28, 0x72, 0x9f,
	0x0b, 0xd9, 0xdc, 0x3b, 0x2d, 0xb4, 0x8b, 0xde, 0xea, 0xc0, 0xbe, 0x41, 0x6d, 0x44, 0x4a, 0xcb,
	0x3e, 0xdf, 0xfe, 0xa0, 0x89, 0xc2, 0x3a, 0xb8, 0xf7, 0x14, 0x6b, 0xba, 0xec, 0x2d, 0x2f, 0x97,
	0xe4, 0xc2, 0x0f, 0xe7, 0xa4, 0xc9, 0xb2, 0xb7, 0x3a, 0xe0, 0x09, 0x00, 0xfd, 0x9a, 0x05, 0xab,
	0xba, 0x4d, 0x57, 0x17, 0x33, 0xee, 0xb0, 0x2b, 0x38, 0x1e, 0xf2, 0x49, 0x44, 0x53, 0xe2, 0x6a,
	0x40, 0xc9, 0x85, 0x2e, 0xf4, 0xb7, 0x12, 0x6e, 0x52, 0x82, 0x31, 0xa8, 0x5e, 0x27, 0xcd, 0x7d,
	0xa2, 0x58, 0x22, 0xc2, 0xfe, 0x3d, 0xc5, 0xcb, 0xc9, 0xdc, 0x76, 0xd9, 0xd3, 0xd7, 0xec, 0x25,
	0x54, 0x8c, 0x8c, 0xad, 0x66, 0xaf, 0xa1, 0xa1, 0x9f, 0x7a, 0x24, 0xe7, 0xa1, 0x1a, 0xa9, 0x28,
	0xe0, 0xdf, 0xb1, 0x05, 0xa5, 0x88, 0xe4, 0x4c, 0x70, 0x49, 0x49, 0x36, 0x3d, 0xb3, 0x37, 0x80,
	0x06, 0xf0, 0x31, 0x14, 0xbe, 0x3a, 0x3f, 0xb3, 0x88, 0xbd, 0xdd, 0x44, 0xf7, 0xc2, 0x22, 0x0a,
	0x06, 0xf1, 0x0a, 0x6a, 0x06, 0x31, 0xe4, 0xca, 0x4a, 0x17, 0x8d, 0x74, 0x07, 0xea, 0xdb, 0xe9,
	0x0c, 0xbb, 0x6b, 0xe4, 0xb7, 0x47, 0x1e, 0x67, 0x03, 0xfb, 0xb9, 0x03, 0xf4, 0x85, 0x08, 0xc9,
	0xe7, 0x16, 0x51, 0xca, 0x6d, 0xa9, 0x1f, 0x2b, 0x92, 0x56, 0xbe, 0xba, 0xc9, 0x9f, 0xfd, 0x3e,
	0x84, 0xaa, 0x06, 0x46, 0x14, 0x2d, 0x82, 0x09, 0x61, 0x17, 0x4a, 0x23, 0x52, 0x5f, 0xf5, 0x2a,
	0x1d, 0xad, 0xb6, 0xbb, 0xb3, 0xbd, 0x89, 0xad, 0x46, 0x72, 0xdb, 0x58, 0x75, 0x07, 0xdf, 0x41,
	0xe9, 0x7a, 0xcd, 0x61, 0x12, 0x30, 0x16, 0xa0, 0x75, 0x6c, 0x42, 0x46, 0x77, 0xcc, 0xc1, 0x01,
	0xe0, 0x1a, 0xbd, 0x0a, 0x43, 0xf1, 0x53, 0x2b, 0x33, 0x25, 0x4d, 0x5b, 0xb2, 0x5a, 0x1c, 0xe6,
	0xe0, 0x7b, 0x78, 0x92, 0x5a, 0xe4, 0xf2, 0xcd, 0x65, 0x09, 0x8e, 0x6c, 0xc1, 0x90, 0x2b, 0xe6,
	0xe0, 0x25, 0x3c, 0xdd, 0xa2, 0xbb, 0x17, 0x0f, 0x9d, 0x42, 0x87, 0x99, 0x83, 0x7d, 0xa8, 0x6f,
	0x0c, 0xe3, 0x7c, 0x45, 0xc6, 0x0c, 0xe3, 0xb5, 0x63, 0x00, 0x8d, 0x8d, 0x63, 0xbd, 0xe1, 0x59,
	0x92, 0x17, 0xb6, 0x24, 0x89, 0x67, 0x5a, 0x72, 0x5a, 0xc9, 0xb3, 0xe8, 0x5e, 0x2e, 0xa1, 0xb6,
	0xb1, 0x7c, 0x09, 0xa6, 0xf4, 0xe8, 0x69, 0x7a, 0x50, 0x4e, 0xbf, 0x34, 0x8f, 0xfd, 0x6f, 0xde,
	0x40, 0x25, 0x65, 0xfb, 0x31, 0x9e, 0x24, 0xc9, 0x9c, 0x2f, 0xd7, 0x2e, 0x53, 0x0f, 0xca, 0x69,
	0xf8, 0x1f, 0xba, 0x48, 0xd9, 0xff, 0xeb, 0xa2, 0x0b, 0xee, 0x8d, 0x2f, 0x1f, 0xfa, 0x16, 0x92,
	0x5f, 0x3a, 0x73, 0xf0, 0x2d, 0x1c, 0x78, 0x34, 0x15, 0x0b, 0xc2, 0x67, 0x36, 0xba, 0xab, 0xe2,
	0xed, 0x81, 0x7e, 0x72, 0xfe, 0x27, 0x00, 0x00, 0xff, 0xff, 0x65, 0xce, 0x23, 0x7e, 0xa8, 0x06,
	0x00, 0x00,
}
